// export const REST_API = "https://api-okin.onrender.com/"
// export const REST_API = "https://soft-uni-react-rest-2023-viktorshandrov.vercel.app/"
export const REST_API = "http://localhost:3000/"
export const facebookAppId = "350005497676561"
// export const googleTranslateAPIKey = "AIzaSyCwcafxQT_4clYPFoz6pR5C3KOAbNhvTc8"
export const googleClientId = "638123872925-ss6qml6jnp2ltb4v11jtd63lkhgmrikk.apps.googleusercontent.com"
export const translationAPI = "https://theconfederacy.serveo.net"
export const googleClientSecret = "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"