const jwt = require("jsonwebtoken")
const util = require('util');
const path = require("path");
exports.sign = util.promisify(jwt.sign)
exports.verify = util.promisify(jwt.verify)





exports.isProduction = false


process.env.GOOGLE_APPLICATION_CREDENTIALS =path.join(__dirname,'./gc-cred.json')
exports.port = 3000
exports.secret = "kjsdhgLKJGHDLKJGHkljhlkjhh43iu4h8osioduhfis"
exports.FEdomain = "http://127.0.0.1:5173"
exports.testTypes ={
    randomWords:"randomWords",
    textWords:"textWords",
    textQuestions:"textQuestions"
}
exports.GoogleTranslateAPI_KEY = "AIzaSyCwcafxQT_4clYPFoz6pR5C3KOAbNhvTc8"
exports.chatgptAccessToken = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJjYXJpdmFuODEyNzQ5ODlAcHJvdG9ubWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sImh0dHBzOi8vYXBpLm9wZW5haS5jb20vYXV0aCI6eyJwb2lkIjoib3JnLTNmMW05QjY4ZkxOQnJVMUxKc0RlM1NwOSIsInVzZXJfaWQiOiJ1c2VyLVpUS09OdkM4VUVyMWFIeDljU3l3Zk5RRCJ9LCJpc3MiOiJodHRwczovL2F1dGgwLm9wZW5haS5jb20vIiwic3ViIjoiYXV0aDB8NjU1ZTE2NjZmZWY3NjViZGVmOTZlNjA3IiwiYXVkIjpbImh0dHBzOi8vYXBpLm9wZW5haS5jb20vdjEiLCJodHRwczovL29wZW5haS5vcGVuYWkuYXV0aDBhcHAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTcwMDY2NTEzMCwiZXhwIjoxNzAxNTI5MTMwLCJhenAiOiJUZEpJY2JlMTZXb1RIdE45NW55eXdoNUU0eU9vNkl0RyIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgbW9kZWwucmVhZCBtb2RlbC5yZXF1ZXN0IG9yZ2FuaXphdGlvbi5yZWFkIG9yZ2FuaXphdGlvbi53cml0ZSBvZmZsaW5lX2FjY2VzcyJ9.hbJwi105EMnC3mMCxXrSC7vSBld66371eLeIANuEvSvlV-tXt23h8SlYObEE0DBIsfNDozaZZnGPqt2wu3aiCxtQYrKWNpa0v00oDcxbAvlWEx9Qni-dyo6A9KipM3F6JyoG4jrV9k52EQDq600nfS2BYEAnGBL8kMESA7fiRmMUB0Jlq9upaZRo9CGaF5XqPixJxRbdNMEMVgO4Fnu-2lPFgIp8Fzfflg-qM7rBbmufE3TWIJxb_hUijnRf2rc0tUhxl8syjQsnUn8x2uoUIuCi3irav_xWtJQD1L11kEa3VqOTlSHCDwOiPoqN7bg50Xt8A0pQozVai4EV8j8a1Q"
exports.stripeSecretKey="sk_test_51OEwwSAPrNaPFyVR8ratcB8BTCUKEMzYiSIF8iQiBNBzOmr2olTnhDeuRC0bAAdBqrUyisTg1CN4hEVFSapAmUnV00QqAC84Oj"
exports.openAIAPIkey = "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"
exports.openAIPReoxyToken = "pk-YkGnWlSytCvQzNQVUvPYkfRvCdFfxmFKcgGRYZAEdrXyHkaY"
exports.dbxAccessToken = "sl.Bqd8661L9fVn0Wf6cHyqhSu7SKPPCddVXUsBYpvoj9xzLqXuJMr0Jdx5AOrYoAJk8QGLjYnOXLo3wvsDQp2yQcK1tRX7nHoceo-af89pRK3-pAURe5DmR8DkmnzANiTFdPZ_to_WFBVq"
exports.commonWords = [
    "a",
    "about",
    "above",
    "after",
    "again",
    "against",
    "ain't",
    "all",
    "am",
    "an",
    "and",
    "any",
    "are",
    "aren't",
    "as",
    "at",
    "be",
    "because",
    "been",
    "before",
    "being",
    "below",
    "between",
    "both",
    "but",
    "by",
    "can't",
    "cannot",
    "could",
    "couldn't",
    "did",
    "didn't",
    "do",
    "does",
    "doesn't",
    "doing",
    "don't",
    "down",
    "during",
    "each",
    "few",
    "for",
    "from",
    "further",
    "had",
    "hadn't",
    "has",
    "hasn't",
    "have",
    "haven't",
    "having",
    "he",
    "he'd",
    "he'll",
    "he's",
    "her",
    "here",
    "here's",
    "hers",
    "herself",
    "him",
    "himself",
    "his",
    "how",
    "how's",
    "i",
    "i'd",
    "i'll",
    "i'm",
    "i've",
    "if",
    "in",
    "into",
    "is",
    "isn't",
    "it",
    "it's",
    "its",
    "itself",
    "let's",
    "me",
    "more",
    "most",
    "mustn't",
    "my",
    "myself",
    "no",
    "nor",
    "not",
    "of",
    "off",
    "on",
    "once",
    "only",
    "or",
    "other",
    "ought",
    "our",
    "ours",
    "ourselves",
    "out",
    "over",
    "own",
    "same",
    "shan't",
    "she",
    "she'd",
    "she'll",
    "she's",
    "should",
    "shouldn't",
    "so",
    "some",
    "such",
    "than",
    "that",
    "that's",
    "the",
    "their",
    "theirs",
    "them",
    "themselves",
    "then",
    "there",
    "there's",
    "these",
    "they",
    "they'd",
    "they'll",
    "they're",
    "they've",
    "this",
    "those",
    "through",
    "to",
    "too",
    "under",
    "until",
    "up",
    "very",
    "was",
    "wasn't",
    "we",
    "we'd",
    "we'll",
    "we're",
    "we've",
    "were",
    "weren't",
    "what",
    "what's",
    "when",
    "when's",
    "where",
    "where's",
    "which",
    "while",
    "who",
    "who's",
    "whom",
    "why",
    "why's",
    "with",
    "won't",
    "would",
    "wouldn't",
    "you",
    "you'd",
    "you'll",
    "you're",
    "you've",
    "your",
    "yours",
    "yourself",
    "yourselves",
];
